//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents
    {
        public int documentid { get; set; }
        public int userid { get; set; }
        public int hospitalid { get; set; }
        public int doctorid { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public int recordtype { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string filepath { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual hospitals hospitals { get; set; }
        public virtual recordtypes recordtypes { get; set; }
        public virtual health_users health_users { get; set; }
    }
}
